jobs:
  build:
    name: Check for Headers
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - continue-on-error: true
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: json
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Check for headers
      run: "ok=1\nreadarray -t files <<<\"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified\
        \ }}')\"\nfor file in ${files[@]}; do\n  if [[ ($file == *\".java\") ]]; then\n\
        \    if ! grep -q Copyright \"$file\"; then\n      ok=0\n      echo \"Copyright\
        \ header not found in $file\"\n    fi\n  fi\ndone\nif [[ $ok == 0 ]]; then\n\
        \  exit 1\nelse\n  GREEN=\"\\e[32m\"\n  echo -e \"${GREEN}All changed & added\
        \ files have been scanned. Result: no headers are missing.${ENDCOLOR}\"\n\
        fi\n"
name: Check for Headers in Source Code
on:
  repository_dispatch:
    types: trigger-ga___headerchecker.yml
